// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyBDVvy6TKl9afRNt0AhNtWqc-4qzFUGLhc",
  authDomain: "vendegkonyv-94778.firebaseapp.com",
  projectId: "vendegkonyv-94778",
  storageBucket: "vendegkonyv-94778.appspot.com",
  messagingSenderId: "984534326484",
  appId: "1:984534326484:web:65cb90438909af25bd2f41"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);