openapi: 3.0.0
info:
  title: ReqRes API Példa
  description: Egy API végpont dokumentációja, amely egy felhasználó adatait adja vissza.
  version: 1.0.0
servers:
  - url: https://reqres.in/api
paths:
  /users/{id}:
    get:
      summary: Egy adott felhasználó adatainak lekérdezése
      parameters:
        - name: id
          in: path
          required: true
          description: A felhasználó egyedi azonosítója
          schema:
            type: integer
            example: 2
      responses:
        "200":
          description: Sikeres válasz
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 2
                      email:
                        type: string
                        example: "janet.weaver@reqres.in"
                      first_name:
                        type: string
                        example: "Janet"
                      last_name:
                        type: string
                        example: "Weaver"
                      avatar:
                        type: string
                        format: uri
                        example: "https://reqres.in/img/faces/2-image.jpg"
                  support:
                    type: object
                    properties:
                      url:
                        type: string
                        format: uri
                        example: "https://contentcaddy.io?utm_source=reqres&utm_medium=json&utm_campaign=referral"
                      text:
                        type: string
                        example: "Tired of writing endless social media content? Let Content Caddy generate it for you."
