print("Addjon meg három számot! ")
a = int(input("$"))
b = int(input("$"))
c = int(input("$"))
szamok = []
szamok.append(a)
szamok.append(b)
szamok.append(c)
szamok.sort()
print("A legkisebb szam:", szamok[0], "\nA középső: ", szamok[1], "\nA legnagyobb: ", szamok[2])